name: Maven Package for Windows

#on:
#  release:
#    types: [created]
on: [push]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Emit some env details
      run: echo "Github workspace = ${{ github.workspace }}
    - name: Build with Maven and publish to GitHub Packages Apache Maven
      run: mvn deploy -s ${{ github.workspace }}\settings.xml --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

